services:
  app:
    build: .
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/english_dictionary
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db
      - redis
    command: sh -c "npm install && npm run migrate:prod && npm run start:prod"

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: english_dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
